mycrm/crm/urls.py
from crm import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index,name="sales_index"),
    url(r'^customers/$', views.customers_list,name="customers_list"),
    url(r'^customer/(\d+)/enrollment/$', views.enrollment,name="enrollment"),
    # url(r'^teacher', views.index,name="my_class_list"),
    url(r'^customer/registration/(\d+)/',views.stu_registration,name="stu_registration"),
    url(r'^contract_review/(\d+)/',views.contract_review,name="contract_review"),
    url(r'^payment/(\d+)/',views.payment,name="payment"),
    url(r'^enrollment_rejection/(\d+)/',views.enrollment_rejection,name="enrollment_rejection"),
    # 加超时时间url(r'^customer/registration/(\d+)/(\w+)',views.stu_registration,name="stu_registration"),

]

mycrm/mycrm/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from mycrm import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^$', views.index),
    url(r'^crm/', include("crm.urls")),
    url(r'^student/', include("student.urls")),
    url(r'^teacher/', include("teacher.urls")),
    url(r'^king_admin/', include("king_admin.urls")),
    url(r'^account/login/$', views.access_login),
    url(r'^account/logout/$', views.access_logout,name="access_logout"),
    url(r'^newindex/$', views.newindex),
    url(r'^', views.error),
]

mycrm/teacher/urls.py
from teacher import views
from django.conf.urls import url

urlpatterns = [
    url(r'^my_classes/$', views.my_classes, name="my_classes"),#我的班级
    url(r'^my_classes/(\d+)/$', views.view_class_course, name="view_class_course"),#班级信息
    url(r'^my_classes/(\d+)/(\d+)/$', views.teacher_lesson_detail, name="teacher_lesson_detail"),#课程详情
    url( r'^homeworks/(\d+)/(\d+)/(\d+)/$', views.download_homework, name='download_homework' ),  # 作业下载
    url(r'$', views.teacher_index,name="teacher_index"),



]

mycrm/crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,PermissionsMixin
)
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

# Create your models here.
class Customer(models.Model):
    '''客户信息表：
    主要给销售人员用，存储所有客户信息，里面要记录客户来源＼姓名＼qq＼客户来源＼咨询的内容等,
    客户只要没报名，你没理由要求人家必须告诉你真实姓名及其它更多私人信息呀'''
    name = models.CharField(verbose_name="姓名",max_length=32,blank=True,null=True,help_text='用户报名后请改为真实姓名')
    #客户在咨询时，多是通过qq,所以这里就把qq号做为唯一标记客户的值，不能重复
    qq = models.CharField(verbose_name="qq号",max_length=64,unique=True,help_text=u'QQ号必须唯一')
    qq_name = models.CharField(verbose_name="qq名称",max_length=64,blank=True,null=True)
    id_num = models.CharField(verbose_name="身份证",max_length=64,blank=True,null=True)
    email = models.EmailField(verbose_name="邮箱",max_length=64,blank=True,null=True)
    source_choices = ((0,'转介绍'),
                      (1,'qq'),
                      (2,'微信'),
                      (3,'官方论坛'),
                      (4,'网上搜索'),
                      (5,'其他'),
                    )
    #这个客户来源渠道是为了以后统计各渠道的客户量＼成单量，先分类出来
    source = models.SmallIntegerField(verbose_name="来源",choices=source_choices)
    referral_from = models.CharField(verbose_name="转介绍人qq",max_length=64,blank=True,null=True)
    #已开设的课程单独搞了张表，客户想咨询哪个课程，直接在这里关联就可以
    consult_course = models.ForeignKey("Course",verbose_name="咨询课程",on_delete=models.CASCADE)
    content = models.TextField(verbose_name="咨询详情")
    #课程顾问很得要噢，每个招生老师录入自己的客户
    tags = models.ManyToManyField("Tag",blank=True,verbose_name="标签",)
    consultant = models.ForeignKey("UserProfile",verbose_name="课程顾问",on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name="咨询日期",auto_now_add=True)
    status_choices = ((0,"未报名"),
                      (1,"已报名")
                      )
    status = models.IntegerField(verbose_name="报名状态",default=0,choices=status_choices,help_text="选择客户此时的状态")

    def __str__(self):
        return "QQ:%s,Name:%s" %(self.qq,self.name)

    class Meta:
        verbose_name = "客户信息"
        verbose_name_plural = "客户信息"
        ordering = ['id']

class Tag(models.Model):
    '''标签'''
    name = models.CharField(unique=True,max_length=32)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Tag标签"
        verbose_name_plural = "Tag标签"
class CustomerFollowUp(models.Model):
    '''存储客户的后续跟进信息,客户跟进表，这张表的意义很容易理解， 一个客户今天咨询后，
    你录入到了客户信息表，但他没报名， 所以过了一段时间，销售还得再跟他聊聊吧，聊完后，
    结果又没报，那也得纪录下来吧，因为每个销售每天要聊很多人，你不纪录的话， 可能下次再跟这个人聊时，
    你早已忘记上次聊了什么了， 这样会让客户觉得这个销售不专业，相反，如果把每次跟进的内容都纪录下来，
    过了几个月，这个客户再跟你聊时，竟然发现，你还记得他的所有情况，他就觉得你很重视他，说不定一感动就报名了，
    哈哈。 所以，一条客户信息可能会对应多条跟进记录，是个1对多的关系，必须单独搞张表来记录'''
    customer = models.ForeignKey("Customer",verbose_name="所咨询客户",on_delete=models.CASCADE)
    content = models.TextField(verbose_name="跟进内容")
    consultant = models.ForeignKey("UserProfile",verbose_name="跟踪人",on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name="跟进日期",auto_now_add=True)
    status_choices = ((1,"近期无报名计划"),
                      (2,"2个月内报名"),
                      (3,"1个月内报名"),
                      (4,"2周内报名"),
                      (5,"1周内报名"),
                      (6,"2天内报名"),
                      (7,"已报名"),
                      (8,"已交全款"),
                      )
    status = models.IntegerField(verbose_name="状态",choices=status_choices,help_text="选择客户此时的状态")

    def __str__(self):
        return "QQ:%s -- Status:%s" %(self.customer.qq,self.status)

    class Meta:
        verbose_name = "CustomerFollowUp客户跟进表"
        verbose_name_plural = "CustomerFollowUp客户跟进表"

class Enrollment(models.Model):
    '''存储已报名学员的信息,这里为什么要把客户信息表 和 这个学员报名表分开呢？ 因内一个学员可以报多个课程 ，每个课程 都需要单独记录学习成绩呀什么的，
        ,所以每报一个课程 ，就在这里生成 一条相应的报名记录'''
    #所有报名的学生 肯定是来源于客户信息表的，先咨询，后报名嘛
    customer = models.ForeignKey("Customer",on_delete=models.CASCADE)
    enrolled_class = models.ForeignKey("ClassList",verbose_name="所报班级",on_delete=models.CASCADE)
    consultant = models.ForeignKey("UserProfile",verbose_name="课程顾问",on_delete=models.CASCADE)
    contract_agreed = models.BooleanField("学员已同意合同",default=0)
    contract_approved = models.BooleanField("审批通过", help_text="合同已审核",default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s" %(self.customer,self.enrolled_class)

    class Meta:
        # #这里为什么要做个unique_together联合唯一？因为老男孩有很多个课程， 学生学完了一个觉得好的话，以后还可以再报其它班级，
        #每报一个班级，就得单独创建一条报名记录，所以这里想避免重复数据的话，就得搞个"客户 + 班级"的联合唯一喽
        unique_together = ('customer','enrolled_class')
        verbose_name = "Enrollment学员报名表"
        verbose_name_plural ="Enrollment学员报名表"

class ClassList(models.Model):
    '''存储班级信息,学生以班级为单位管理，这个表被学员表反向关联， 即每个学员报名时需要选择班级'''
    class_name = models.CharField(verbose_name="班级名称",max_length=32,blank=True,null=False,unique=True)
    branch = models.ForeignKey("Branch",verbose_name="校区",on_delete=models.CASCADE)
    course = models.ForeignKey("Course",verbose_name="课程",on_delete=models.CASCADE)
    class_type_choices = ((0,'面授(脱产)'),(1,'面授(周末)'),(2,'随到随学网络'))
    class_type = models.SmallIntegerField(choices=class_type_choices,default=0,verbose_name="班级类型")
    semester = models.PositiveSmallIntegerField(verbose_name="学期")
    teachers = models.ManyToManyField("UserProfile")
    start_date = models.DateField(verbose_name="开班日期")
    end_date = models.DateField(verbose_name="结业日期",blank=True,null=True)
    contract = models.ForeignKey("Contract",blank=True,null=True,on_delete=models.CASCADE)

    def __str__(self):
        return "%s-%s-%s"%(self.branch,self.course,self.class_name)

    class Meta:
        verbose_name = "ClassList班级表"
        verbose_name_plural ="ClassList班级表"

class Contract(models.Model):
    '''合同表'''
    name = models.CharField("合同名称",max_length=64,unique=True)
    template = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = " Contract合同表"
        verbose_name_plural ="Contract合同表"

class Course(models.Model):
    '''存储所开设课程的信息'''
    name = models.CharField(verbose_name="课程名",max_length=64,unique=True)
    price = models.PositiveSmallIntegerField(verbose_name="课程价格")
    outline = models.TextField(verbose_name="课程大纲")
    period  = models.IntegerField(verbose_name="课程周期(Month)")

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Course课程信息表"
        verbose_name_plural ="Course课程信息表"


class CourseRecord(models.Model):
    '''存储各班级的上课记录,'''
    #每个班级都要上很多次课，讲师每上一次课的纪录都要纪录下来，以后可以方便统计讲师工资什么的
    from_class = models.ForeignKey("ClassList",verbose_name="班级",on_delete=models.CASCADE)
    day_num = models.PositiveSmallIntegerField(verbose_name="第几节课（天）")
    teacher = models.ForeignKey("UserProfile", verbose_name="讲师",on_delete=models.CASCADE)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField(max_length=128,blank=True,null=True,verbose_name="作业标题")
    homework_content = models.TextField(blank=True,null=True,verbose_name="作业内容")
    outline = models.TextField(verbose_name="本节课程大纲")
    date = models.DateTimeField(verbose_name="上课日期",auto_now_add=True)

    def __str__(self):
        return "%s %s" %(self.from_class,self.day_num)

    class Meta:
        unique_together = ('from_class','day_num')
        verbose_name = "CourseRecord上课记录表"
        verbose_name_plural ="CourseRecord上课记录表"

class StudyRecord(models.Model):
    '''存储所有学员的详细的学习成绩情况'''
    student = models.ForeignKey("Enrollment",verbose_name="学员",on_delete=models.CASCADE)
    course_record = models.ForeignKey("CourseRecord", verbose_name="第几天课程",on_delete=models.CASCADE)
    record_choices = ((0,"已签到"),
                      (1,"迟到"),
                      (2,"缺勤"),
                      (3,"早退"),
                      )
    record = models.IntegerField(verbose_name="上课纪录",choices=record_choices,default=0)
    score_choices = ((100, 'A+'),   (90,'A'),
                     (85,'B+'),     (80,'B'),
                     (70,'B-'),     (60,'C+'),
                     (50,'C'),      (40,'C-'),
                     (-50,'D'),       (0,'N/A'),
                     (-100,'COPY'), (-1000,'FAIL'),
                     )
    score = models.IntegerField(verbose_name="本节成绩",choices=score_choices,default=0)
    date = models.DateTimeField(auto_now_add=True)
    memo = models.TextField(verbose_name="评语",blank=True,null=True)

    def __str__(self):
        return "%s %s %s" %(self.student,self.course_record,self.score)

    class Meta:
        #一个学员，在同一节课只可能出现一次，所以这里把course_record ＋ student 做成联合唯一
        unique_together = ('course_record','student')
        verbose_name = "StudyRecord学习成绩表"
        verbose_name_plural ="StudyRecord学习成绩表"

# class UserProfile(models.Model):
#     '''账号表，这里我们用django自带的认证系统，并对其进行自定制'''
#     user = models.OneToOneField(User,on_delete=models.CASCADE,)
#     name = models.CharField(max_length=32,verbose_name="用户姓名")
#     roles = models.ManyToManyField("Role",blank=True,verbose_name="用户角色")
#
#     def __str__(self):
#         return self.name
#     class Meta:
#         verbose_name = "UserProfile账号表"
#         verbose_name_plural ="UserProfile账号表"
class UserProfileManager(BaseUserManager):
    #创建用户的方法
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )
        user.is_active = True
        user.set_password(password)

mycrm/teacher/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.http import StreamingHttpResponse
from crm import models
from mycrm import settings
import os,json,time
from crm.permissions import permission
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def teacher_index(request):
    print(request.getHeader("user-agent"))
    return render(request,'newindex.html')

@login_required
def my_classes(request):
    '''我的班级'''
    return render(request,'teacher/my_classes.html')

@login_required
def view_class_course(request,class_id):
    '''班级信息'''

    class_obj = models.ClassList.objects.get(id=class_id)
    courserecordlist = class_obj.courserecord_set.all()
    print(courserecordlist)
    return render(request,'teacher/class_course.html',{"class_obj":class_obj,"courserecordlist":courserecordlist})


@login_required
def teacher_lesson_detail(request,class_id,courserecordlist_id):
    '''课程详细'''

    class_obj = models.ClassList.objects.get(id=class_id)
    courserecordlist = class_obj.courserecord_set.get( id=courserecordlist_id )
    studyrecord_list = courserecordlist.studyrecord_set.all()
    return render(request,'teacher/teacher_lesson_detail.html',{'class_ojb':class_obj,'courserecordlist':courserecordlist,'studyrecord_list':studyrecord_list})


def download_homework(request,class_id,course_record_id,studyrecrd_id):
    '''下载作业'''
    homework_path = '%s/%s/%s/%s/' % (settings.HOMEWORK, class_id,course_record_id,studyrecrd_id)  # 作业目录
    def file_iterator(file_path, chunk_size=512):  # 获取文件 #chunk_size每次读取的大小 #文件迭代器
         with open( file_path, 'rb', ) as f:  # 循环打开 文件#以二进制读模式打开
             while True:  # 如果有文件
                 byte = f.read( chunk_size )  # read读最多大小字节,作为字节返回。#获取文件大小
                 if byte:
                     yield byte  # 返回 yield 后的值作为第一次迭代的返回值. 循环下一次，再返回，直到没有可以返回的。
                 else:
                     break  # 没有字节就中止

    if os.path.exists( homework_path ):  # 判断目录是否存在
        try:#防止后台误删文件
            file_list = os.listdir( homework_path )  # 取目录 下的文件
            print( '文件名：', file_list, type( file_list ) )
            file_path = '%s%s' % (homework_path, file_list[0])  # 下载文件路径
            print( '下载文件路径：', file_path )
            response = StreamingHttpResponse( file_iterator( file_path ) )  # StreamingHttpResponse是将文件内容进行流式传输
            response['Content-Type'] = 'application/octet-stream'  # 文件类型 #应用程序/octet-stream.*（ 二进制流，不知道下载文件类型）
            file_name = 'attachment;filename=%s' % file_list[0]  # 文件名字# 支持中文
            response['Content-Disposition'] = file_name.encode()  # 支持中文#编码默认encoding='utf-8'
            return response  # 返回下载 请求的内容
        except:
            return HttpResponse("下载出错")
    return redirect( '/teacher/my_classes/%s/%s/' % (class_id, course_record_id) )  # 返回##本节课的学员

mycrm/templates/teacher/class_course.html
{% extends 'newindex.html' %}
{% load stu_tags %}

{# <div>#}
{#        <ul class="nav nav-tabs">#}
{#            <li role="presentation" class="active"><a href="/student/">我的课程</a></li>#}
{#            <li role="presentation"><a href="#">班级</a></li>#}
{#            <li role="presentation"><a href="#">作业详情</a></li>#}
{#        </ul>#}
{#    </div>#}

{% block page-content %}

    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">课程信息</h3>
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>课程节次</th>
                        <th>签到状态</th>
                        <th>本节作业</th>
                        <th>上课日期</th>
                        <th>作业标题</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for courserecord in courserecordlist %}
                        <tr>
                            <td>
                                第{{ courserecord.day_num }}节
                            </td>
                            <td><a style="color: #1ABB9C" href="/king_admin/crm/studyrecord/?course_record={{ courserecord.id }} ">点名/成绩</a></td>
                            <td>
                                {% if courserecord.has_homework %}
                                    有
                                    {% else  %}
                                    无
                                {% endif %}
                            </td>
                        <td>{{ courserecord.date }}</td>
                        <td>{{ courserecord.homework_title }}</td>
{#                        <td><pre style="width: 240px;height: 60px">{{ courserecord.outline }} </pre></td>#}
                        <td><a style="color: #1ABB9C" href="{% url 'teacher_lesson_detail' class_obj.id courserecord.id %}">查看详细</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!--===================================================-->
        <!-- End Striped Table -->

    </div>

{% endblock %}

mycrm/templates/teacher/my_classes.html
{% extends 'newindex.html' %}
{% load stu_tags %}

{# <div>#}
{#        <ul class="nav nav-tabs">#}
{#            <li role="presentation" class="active"><a href="/student/">我的课程</a></li>#}
{#            <li role="presentation"><a href="#">班级</a></li>#}
{#            <li role="presentation"><a href="#">作业详情</a></li>#}
{#        </ul>#}
{#    </div>#}

{% block page-content %}

    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title">班级列表</h4>
            {#            <a href="/king_admin/crm/classlist/add/" class="pull-right">+添加班级</a>#}
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>班级名称</th>
                        <th>班级(学期)</th>
                        <th>类型</th>
                        <th>开课日期</th>
                        <th>开课总节次</th>
                        <th>已上节次</th>
                        <th>学员数量</th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for class_obj in request.user.classlist_set.select_related %}
                        <tr>
                            <td><a href="{% url 'view_class_course'  class_obj.id %}" class="btn-link">{{ class_obj.class_name }}</a></td>
                            <td>{{ class_obj.course }}({{ class_obj.semester }})</td>
                            <td>{{ class_obj.get_class_type_display }}</td>
                            <td>
                                {{ class_obj.start_date }}
                            </td>
                            <td>{{ class_obj.total_class_nums }}</td>
                            <td>{% if class_obj.class_type == 0 %}
                                {{ class_obj.courserecord_set.select_related.count }}
                            {% elif class_obj.class_type == 1 %}

                                na
                            {% endif %}
                            </td>
                            <td>
                                {{ class_obj.enrollment_set.select_related.count }}
                            </td>
                            <td><a class="btn-link"
                                   href="/king_admin/crm/courserecord/?from_class={{ class_obj.id }}">上课纪录</a></td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
        <!--===================================================-->
        <!-- End Striped Table -->

    </div>

{% endblock %}

mycrm/templates/teacher/teacher_lesson_detail.html
{% extends 'newindex.html' %}
{% load stu_tags %}

{# <div>#}
{#        <ul class="nav nav-tabs">#}
{#            <li role="presentation" class="active"><a href="/student/">我的课程</a></li>#}
{#            <li role="presentation"><a href="#">班级</a></li>#}
{#            <li role="presentation"><a href="#">作业详情</a></li>#}
{#        </ul>#}
{#    </div>#}

{% block page-content %}

    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title">课程详细</h4>
            {#            <a href="/king_admin/crm/classlist/add/" class="pull-right">+添加班级</a>#}

        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <li>
                    作业标题:
                    <pre>{{ courserecordlist.homework_title }}</pre>
                </li>
                <li>
                    作业要求:
                    <pre>{{ courserecordlist.homework_content }}</pre>
                </li>
                <li>
                    本节课程大纲:
                    <pre>{{ courserecordlist.outline }}</pre>
                </li>
                <br>
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th>学员姓名</th>
                        <th>签到状态</th>
                        <th>作业</th>
                        <th>批改情况</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for studyrecrd in studyrecord_list %}
                        <tr>
                            <td>{{ studyrecrd.student.customer.name }}</td>
                            <td>{{ studyrecrd.get_record_display }}</td>
                            <td>
                                <a style="color: #204d74" href="{% url 'download_homework' class_ojb.id studyrecrd.course_record.id studyrecrd.id %}">下载</a>
                            <td>
                                {% if studyrecrd.course_record.has_homework %}
                                    {% if studyrecrd.score == 0 %}
                                        <span
                                                style="color: darkred">未批改</span>
                                    {% else %}
                                        <span
                                                style="color: #0088cc">已批改</span>
                                    {% endif %}
                                {% endif %}
                            </td>
                            <td><a target="_blank"
                                   href="/king_admin/crm/studyrecord/{{ studyrecrd.id }}/change/"
                                   style="color: #1ABB9C">查看</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>


            </div>
        </div>
        <!--===================================================-->
        <!-- End Striped Table -->

    </div>

{% endblock %}