mycrm/crm/urls.py
from crm import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index,name="sales_index"),
    url(r'^customers/$', views.customers_list,name="customers_list"),
    url(r'^customer/(\d+)/enrollment/$', views.enrollment,name="enrollment"),
    # url(r'^teacher', views.index,name="my_class_list"),
    url(r'^customer/registration/(\d+)/',views.stu_registration,name="stu_registration"),
    url(r'^contract_review/(\d+)/',views.contract_review,name="contract_review"),
    url(r'^payment/(\d+)/',views.payment,name="payment"),
    url(r'^enrollment_rejection/(\d+)/',views.enrollment_rejection,name="enrollment_rejection"),
    # 加超时时间url(r'^customer/registration/(\d+)/(\w+)',views.stu_registration,name="stu_registration"),

]

mycrm/mycrm/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from mycrm import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^$', views.index),
    url(r'^crm/', include("crm.urls")),
    url(r'^student/', include("student.urls")),
    url(r'^teacher/', include("teacher.urls")),
    url(r'^king_admin/', include("king_admin.urls")),
    url(r'^account/login/$', views.access_login),
    url(r'^account/logout/$', views.access_logout,name="access_logout"),
    url(r'^newindex/$', views.newindex),
    url(r'^', views.error),
]

mycrm/student/urls.py
from student import views
from django.conf.urls import url

urlpatterns = [
    url(r'^student/$', views.stu_my_classes,name="stu_my_classes"),
    url(r'^studyrecords/(\d+)$', views.studyrecords,name="studyrecords"),
    url(r'^homework_detail/(\d+)$', views.homework_detail,name="homework_detail"),
    url(r'^delete_file/$', views.delete_file,name="delete_file"),
    url(r'^', views.stu_index,name="stu_index"),

]

mycrm/crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,PermissionsMixin
)
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

# Create your models here.
class Customer(models.Model):
    '''客户信息表：
    主要给销售人员用，存储所有客户信息，里面要记录客户来源＼姓名＼qq＼客户来源＼咨询的内容等,
    客户只要没报名，你没理由要求人家必须告诉你真实姓名及其它更多私人信息呀'''
    name = models.CharField(verbose_name="姓名",max_length=32,blank=True,null=True,help_text='用户报名后请改为真实姓名')
    #客户在咨询时，多是通过qq,所以这里就把qq号做为唯一标记客户的值，不能重复
    qq = models.CharField(verbose_name="qq号",max_length=64,unique=True,help_text=u'QQ号必须唯一')
    qq_name = models.CharField(verbose_name="qq名称",max_length=64,blank=True,null=True)
    id_num = models.CharField(verbose_name="身份证",max_length=64,blank=True,null=True)
    email = models.EmailField(verbose_name="邮箱",max_length=64,blank=True,null=True)
    source_choices = ((0,'转介绍'),
                      (1,'qq'),
                      (2,'微信'),
                      (3,'官方论坛'),
                      (4,'网上搜索'),
                      (5,'其他'),
                    )
    #这个客户来源渠道是为了以后统计各渠道的客户量＼成单量，先分类出来
    source = models.SmallIntegerField(verbose_name="来源",choices=source_choices)
    referral_from = models.CharField(verbose_name="转介绍人qq",max_length=64,blank=True,null=True)
    #已开设的课程单独搞了张表，客户想咨询哪个课程，直接在这里关联就可以
    consult_course = models.ForeignKey("Course",verbose_name="咨询课程",on_delete=models.CASCADE)
    content = models.TextField(verbose_name="咨询详情")
    #课程顾问很得要噢，每个招生老师录入自己的客户
    tags = models.ManyToManyField("Tag",blank=True,verbose_name="标签",)
    consultant = models.ForeignKey("UserProfile",verbose_name="课程顾问",on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name="咨询日期",auto_now_add=True)
    status_choices = ((0,"未报名"),
                      (1,"已报名")
                      )
    status = models.IntegerField(verbose_name="报名状态",default=0,choices=status_choices,help_text="选择客户此时的状态")

    def __str__(self):
        return "QQ:%s,Name:%s" %(self.qq,self.name)

    class Meta:
        verbose_name = "客户信息"
        verbose_name_plural = "客户信息"
        ordering = ['id']

class Tag(models.Model):
    '''标签'''
    name = models.CharField(unique=True,max_length=32)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Tag标签"
        verbose_name_plural = "Tag标签"
class CustomerFollowUp(models.Model):
    '''存储客户的后续跟进信息,客户跟进表，这张表的意义很容易理解， 一个客户今天咨询后，
    你录入到了客户信息表，但他没报名， 所以过了一段时间，销售还得再跟他聊聊吧，聊完后，
    结果又没报，那也得纪录下来吧，因为每个销售每天要聊很多人，你不纪录的话， 可能下次再跟这个人聊时，
    你早已忘记上次聊了什么了， 这样会让客户觉得这个销售不专业，相反，如果把每次跟进的内容都纪录下来，
    过了几个月，这个客户再跟你聊时，竟然发现，你还记得他的所有情况，他就觉得你很重视他，说不定一感动就报名了，
    哈哈。 所以，一条客户信息可能会对应多条跟进记录，是个1对多的关系，必须单独搞张表来记录'''
    customer = models.ForeignKey("Customer",verbose_name="所咨询客户",on_delete=models.CASCADE)
    content = models.TextField(verbose_name="跟进内容")
    consultant = models.ForeignKey("UserProfile",verbose_name="跟踪人",on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name="跟进日期",auto_now_add=True)
    status_choices = ((1,"近期无报名计划"),
                      (2,"2个月内报名"),
                      (3,"1个月内报名"),
                      (4,"2周内报名"),
                      (5,"1周内报名"),
                      (6,"2天内报名"),
                      (7,"已报名"),
                      (8,"已交全款"),
                      )
    status = models.IntegerField(verbose_name="状态",choices=status_choices,help_text="选择客户此时的状态")

    def __str__(self):
        return "QQ:%s -- Status:%s" %(self.customer.qq,self.status)

    class Meta:
        verbose_name = "CustomerFollowUp客户跟进表"
        verbose_name_plural = "CustomerFollowUp客户跟进表"

class Enrollment(models.Model):
    '''存储已报名学员的信息,这里为什么要把客户信息表 和 这个学员报名表分开呢？ 因内一个学员可以报多个课程 ，每个课程 都需要单独记录学习成绩呀什么的，
        ,所以每报一个课程 ，就在这里生成 一条相应的报名记录'''
    #所有报名的学生 肯定是来源于客户信息表的，先咨询，后报名嘛
    customer = models.ForeignKey("Customer",on_delete=models.CASCADE)
    enrolled_class = models.ForeignKey("ClassList",verbose_name="所报班级",on_delete=models.CASCADE)
    consultant = models.ForeignKey("UserProfile",verbose_name="课程顾问",on_delete=models.CASCADE)
    contract_agreed = models.BooleanField("学员已同意合同",default=0)
    contract_approved = models.BooleanField("审批通过", help_text="合同已审核",default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s %s" %(self.customer,self.enrolled_class)

    class Meta:
        # #这里为什么要做个unique_together联合唯一？因为老男孩有很多个课程， 学生学完了一个觉得好的话，以后还可以再报其它班级，
        #每报一个班级，就得单独创建一条报名记录，所以这里想避免重复数据的话，就得搞个"客户 + 班级"的联合唯一喽
        unique_together = ('customer','enrolled_class')
        verbose_name = "Enrollment学员报名表"
        verbose_name_plural ="Enrollment学员报名表"

class ClassList(models.Model):
    '''存储班级信息,学生以班级为单位管理，这个表被学员表反向关联， 即每个学员报名时需要选择班级'''
    class_name = models.CharField(verbose_name="班级名称",max_length=32,blank=True,null=False,unique=True)
    branch = models.ForeignKey("Branch",verbose_name="校区",on_delete=models.CASCADE)
    course = models.ForeignKey("Course",verbose_name="课程",on_delete=models.CASCADE)
    class_type_choices = ((0,'面授(脱产)'),(1,'面授(周末)'),(2,'随到随学网络'))
    class_type = models.SmallIntegerField(choices=class_type_choices,default=0,verbose_name="班级类型")
    semester = models.PositiveSmallIntegerField(verbose_name="学期")
    teachers = models.ManyToManyField("UserProfile")
    start_date = models.DateField(verbose_name="开班日期")
    end_date = models.DateField(verbose_name="结业日期",blank=True,null=True)
    contract = models.ForeignKey("Contract",blank=True,null=True,on_delete=models.CASCADE)

    def __str__(self):
        return "%s-%s-%s"%(self.branch,self.course,self.class_name)

    class Meta:
        verbose_name = "ClassList班级表"
        verbose_name_plural ="ClassList班级表"

class Contract(models.Model):
    '''合同表'''
    name = models.CharField("合同名称",max_length=64,unique=True)
    template = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = " Contract合同表"
        verbose_name_plural ="Contract合同表"

class Course(models.Model):
    '''存储所开设课程的信息'''
    name = models.CharField(verbose_name="课程名",max_length=64,unique=True)
    price = models.PositiveSmallIntegerField(verbose_name="课程价格")
    outline = models.TextField(verbose_name="课程大纲")
    period  = models.IntegerField(verbose_name="课程周期(Month)")

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Course课程信息表"
        verbose_name_plural ="Course课程信息表"


class CourseRecord(models.Model):
    '''存储各班级的上课记录,'''
    #每个班级都要上很多次课，讲师每上一次课的纪录都要纪录下来，以后可以方便统计讲师工资什么的
    from_class = models.ForeignKey("ClassList",verbose_name="班级",on_delete=models.CASCADE)
    day_num = models.PositiveSmallIntegerField(verbose_name="第几节课（天）")
    teacher = models.ForeignKey("UserProfile", verbose_name="讲师",on_delete=models.CASCADE)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField(max_length=128,blank=True,null=True,verbose_name="作业标题")
    homework_content = models.TextField(blank=True,null=True,verbose_name="作业内容")
    outline = models.TextField(verbose_name="本节课程大纲")
    date = models.DateTimeField(verbose_name="上课日期",auto_now_add=True)

    def __str__(self):
        return "%s %s" %(self.from_class,self.day_num)

    class Meta:
        unique_together = ('from_class','day_num')
        verbose_name = "CourseRecord上课记录表"
        verbose_name_plural ="CourseRecord上课记录表"

class StudyRecord(models.Model):
    '''存储所有学员的详细的学习成绩情况'''
    student = models.ForeignKey("Enrollment",verbose_name="学员",on_delete=models.CASCADE)
    course_record = models.ForeignKey("CourseRecord", verbose_name="第几天课程",on_delete=models.CASCADE)
    record_choices = ((0,"已签到"),
                      (1,"迟到"),
                      (2,"缺勤"),
                      (3,"早退"),
                      )
    record = models.IntegerField(verbose_name="上课纪录",choices=record_choices,default=0)
    score_choices = ((100, 'A+'),   (90,'A'),
                     (85,'B+'),     (80,'B'),
                     (70,'B-'),     (60,'C+'),
                     (50,'C'),      (40,'C-'),
                     (-50,'D'),       (0,'N/A'),
                     (-100,'COPY'), (-1000,'FAIL'),
                     )
    score = models.IntegerField(verbose_name="本节成绩",choices=score_choices,default=0)
    date = models.DateTimeField(auto_now_add=True)
    memo = models.TextField(verbose_name="评语",blank=True,null=True)

    def __str__(self):
        return "%s %s %s" %(self.student,self.course_record,self.score)

    class Meta:
        #一个学员，在同一节课只可能出现一次，所以这里把course_record ＋ student 做成联合唯一
        unique_together = ('course_record','student')
        verbose_name = "StudyRecord学习成绩表"
        verbose_name_plural ="StudyRecord学习成绩表"

# class UserProfile(models.Model):
#     '''账号表，这里我们用django自带的认证系统，并对其进行自定制'''
#     user = models.OneToOneField(User,on_delete=models.CASCADE,)
#     name = models.CharField(max_length=32,verbose_name="用户姓名")
#     roles = models.ManyToManyField("Role",blank=True,verbose_name="用户角色")
#
#     def __str__(self):
#         return self.name
#     class Meta:
#         verbose_name = "UserProfile账号表"
#         verbose_name_plural ="UserProfile账号表"
class UserProfileManager(BaseUserManager):
    #创建用户的方法
    def create_user(self, email, name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
        )
        user.is_active = True
        user.set_password(password)

mycrm/student/models.py
from django.db import models

# Create your models here.

mycrm/student/views.py
from django.shortcuts import render,HttpResponse
from crm import models
from mycrm import settings
import os,json,time
from crm.permissions import permission

# Create your views here.

@permission.check_permission
def stu_my_classes(request):
    return render(request,'student/stu_my_classes.html')


def stu_index(request):
    return render(request,'newindex.html')

@permission.check_permission
def studyrecords(request,enroll_obj_id):
    enroll_obj = models.Enrollment.objects.get(id=enroll_obj_id)
    return render(request,'student/studyrecords.html',{"enroll_obj":enroll_obj})

def get_uploaded_fileinfo(file_dic,upload_dir):
    #展示上传列表
    for filename in os.listdir(upload_dir):
        abs_file = '%s/%s' % (upload_dir, filename)
        file_create_time = time.strftime("%Y-%m-%d %H:%M:%S",
                                         time.gmtime(os.path.getmtime(abs_file)))
        file_dic['files'][filename] = {'size': os.path.getsize(abs_file) / 1000,
                                           'ctime': file_create_time}
@permission.check_permission
def homework_detail(request,studyrecord_id):
    studyrecord_obj = models.StudyRecord.objects.get(id=studyrecord_id)
    homework_path = "{base_dir}/{class_id}/{course_record_id}/{studyrecord_id}/".format(base_dir=settings.HOMEWORK,
                                                                                            class_id=studyrecord_obj.student.enrolled_class.id,
                                                                                            course_record_id=studyrecord_obj.course_record_id,
                                                                                           studyrecord_id=studyrecord_obj.id)

    response_dic = {'files':{}}

    if not os.path.isdir(homework_path):
            os.makedirs(homework_path,exist_ok=True)
    if request.method =="POST":
        if len(os.listdir(homework_path)) <1:
                #传文件
                for k,file_obj in request.FILES.items():
                    file_type = os.path.splitext(file_obj.name)[1]
                    if file_type in ('.zip'):
                        with open("%s/%s"%(homework_path,file_obj.name),"wb") as f:
                            for chunk in file_obj.chunks():
                                f.write((chunk))
                    else:
                        return HttpResponse(json.dumps({"status":False,"err_msg":"只能上传zip格式的图片"}))
                return HttpResponse(json.dumps({'status': True, }), )
        else:
                return HttpResponse(json.dumps({"status":False,"err_msg":"最多只能传1个文件"}))

    get_uploaded_fileinfo(response_dic, homework_path)
    #print(response_dic)
    return render(request,'student/homework_detail.html',{"studyrecord_obj":studyrecord_obj,"response_dic":response_dic})

def delete_file(request):
    #删除文件
    ret = {}
    if request.method == "POST":
        studyrecord_id=request.POST.get("studyrecord_id")
        filename = request.POST.get("filename")
        studyrecord_obj = models.StudyRecord.objects.get(id=studyrecord_id)
        homework_path = "{base_dir}/{class_id}/{course_record_id}/{studyrecord_id}/".format(base_dir=settings.HOMEWORK,
                                                                                            class_id=studyrecord_obj.student.enrolled_class.id,
                                                                                            course_record_id=studyrecord_obj.course_record_id,
                                                                                            studyrecord_id=studyrecord_obj.id)

        abs_file = '%s/%s' % (homework_path,filename)
        os.remove(abs_file)
        ret["status"]=True
    return HttpResponse(json.dumps(ret))

mycrm/templates/student/homework_detail.html
{% extends 'newindex.html' %}
{% load stu_tags %}

{% block page-content %}
    <div>
        <ul class="nav nav-tabs">
            <li role="presentation"><a href="/student/">我的课程</a></li>
            <li role="presentation"><a href="/student/studyrecords/{{ studyrecord_obj.student.id }}">班级</a></li>
            <li role="presentation" class="active"><a href="#">作业详情</a></li>
        </ul>
    </div>
    <div class="panel panel-default">
        <!-- Default panel contents -->

        <div class="panel-heading">班级：{{ studyrecord_obj.student.enrolled_class }} |
            节次：{{ studyrecord_obj.course_record.day_num }}</div>
        <div class="panel-body">
            <h4>作业标题:<b>{{ studyrecord_obj.course_record.homework_title }}</b></h4>
            <hr>
            <h4>作业详情:
                <pre>{{ studyrecord_obj.course_record.homework_content }}</pre>
            </h4>
            <hr>
            <h4>老师评语:
                <pre>{{ studyrecord_obj.memo }}</pre>
            </h4>
            <hr>
            <h4>本节成绩:<span style="color: red">{{ studyrecord_obj.score }}</span></h4>
            {#    {{ request.user.stu_account }}#}

            <hr>
            <p>已上传文件列表:</p>
            <table id="uploaded-list" class="table table-striped">
                <thead>
                <tr>
                    <th>文件名</th>
                    <th>大小(kb)</th>
                    <th>上传时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for filename, fileinfo in response_dic.files.items %}
                    <tr>
                        <td><a>{{ filename }}</a></td>
                        <td>{{ fileinfo.size }}</td>
                        <td>{{ fileinfo.ctime }}</td>
                        <td><a href="javascript:void(0)"
                               onclick="DeleteFileOnServer('{{ filename }}','{{ studyrecord_obj.id }}')">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <hr>
            <p>请上传作业</p>

            <form id="filedropzone" method="post" action="{{ request.path }}"
                  class="dropzone dz-clickable">{% csrf_token %}
                <div class="dz-default dz-message">
                    <div class="dz-icon icon-wrap icon-circle icon-wrap-md">
                        <i class="fa fa-cloud-upload fa-3x"></i>
                    </div>
                    <div>
                        <p class="dz-text">把作业拖到这里</p>
                        <p class="text-muted">请压缩打包后上传</p>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block bottom-js %}
    <script>
    Dropzone.autoDiscover = false;
        $(document).ready(function () {
            Dropzone.options.filedropzone = {
                url: "{{ request.path }}",
                paramName: "file", // The name that will be used to transfer the file
                maxFilesize: 2, // MB,
                addRemoveLinks: true,
                maxFiles: 2,
                uploadMultiple: true,
                accept: function (file, done) {
                    if (file.name == "github.txt") {
                        alert("Naha, you don't.")
                        {#              done("Naha, you don't.");#}
                    }
                    else {
                        done();
                    }
                }
            }
        });
        // or disable for specific dropzone:
        // Dropzone.options.myDropzone = false;
        myDropzone = new Dropzone("#filedropzone");
        myDropzone.on("addedfile", function (file) {
            /* Maybe display some more file information on your page */
        });
        myDropzone.on("success", function (file, response) {
            /* Maybe display some more file information on your page */
            response = JSON.parse(response);
            if (!response.status) {
                window.alert(response.err_msg);
                window.location.reload()
            } else {
                window.alert("上传成功！");
                window.location.reload()

            }

        })

        function DeleteFileOnServer(filename,studyrecord_id) {
            if (window.confirm('你确定要删除吗？')) {
                $.ajax({
                    url: '/student/delete_file/',
                    type: 'POST',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        "studyrecord_id": studyrecord_id,
                        "filename":filename
                    },
                    success: function (data) {
                        var data = JSON.parse(data);
                        if (data.status) {
                            window.location.reload()
                        }
                        else {
                            window.alert("文件不存在")
                        }
                    }
                })
            }
            else{
                return false
            }

        }
    </script>
{% endblock %}

mycrm/templates/student/stu_my_classes.html
{% extends 'newindex.html' %}
{% load stu_tags %}

{% block page-content %}


    <div class="panel panel-default">
  <!-- Default panel contents -->
{#  <div class="panel-heading">我的课程</div>#}
  <div class="panel-body">
      <table class="table table-hover">
        <thead>
            <tr>
                <th>课程名称</th>
                <th>班级</th>
                <th>开课日期</th>
                <th>结业日期</th>
                <th>课程进度</th>
                <th>总分</th>
                <th>作业管理</th>
            </tr>
        </thead>
          <tbody>
          {% for enroll_obj in request.user.stu_account.enrollment_set.all %}
              <tr>
              <td>{{ enroll_obj.enrolled_class.course }}</td>
              <td>{{ enroll_obj.enrolled_class }}</td>
              <td>{{ enroll_obj.enrolled_class.start_date }}</td>
              <td>{{ enroll_obj.enrolled_class.end_date }}</td>
              <td>已上{{ enroll_obj.enrolled_class.courserecord_set.all.count }}节课</td>
              <td>{% get_score enroll_obj request.user.stu_account as score_data%}
              {{ score_data.score__sum }}</td>
              <td><a href="{% url 'studyrecords' enroll_obj.id%}">查看详情</a></td>



              </tr>
          {% endfor %}
          </tbody>
</table>
{#    {{ request.user.stu_account }}#}
  </div>

</div>
{% endblock %}

mycrm/templates/student/studyrecords.html
{% extends 'newindex.html' %}
{% load stu_tags %}

{% block page-content %}
      <div>
    <ul class="nav nav-tabs">
                        <li role="presentation" ><a href="/student/">我的课程</a></li>
                        <li role="presentation"class="active"><a href="#">班级</a></li>
                        <li role="presentation"><a href="#">作业详情</a></li>
     </ul>
    </div>
    <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">班级：{{ enroll_obj.enrolled_class }}</div>
  <div class="panel-body">
      <table class="table table-hover">
        <thead>
            <tr>
                <th>课程节次</th>
                <th>班级</th>
                <th>作业标题</th>
                <th>签到状态</th>
                <th>有无作业</th>
                <th>我的成绩</th>


            </tr>
        </thead>
          <tbody>
          {% for studyrecord in enroll_obj.studyrecord_set.all %}
              <tr>
              <td>第{{ studyrecord.course_record.day_num }}节</td>
              <td>{{ studyrecord.course_record.date }}</td>
              <td>{{ studyrecord.course_record.homework_title }}</td>
                  <td>{{ studyrecord.get_record_display }}</td>
              <td>{{ studyrecord.course_record.has_homework }} </td>
              <td>{{ studyrecord.get_score_display }}</td>
              <td><a href="{% url 'homework_detail' studyrecord.id%}">作业详情</a></td>
              </tr>
          {% endfor %}
          </tbody>
</table>
{#    {{ request.user.stu_account }}#}
  </div>

</div>
{% endblock %}